### ISSUE TITLE
Confirm button doesn't always react to tap (iPhone / iOS 14.6)

### ISSUE THREAD

**Issue by Madriix** [sweetalert2/sweetalert2#2269] opened 2021-05-30 02:33 UTC
## Current behavior

There is a button problem, sometimes you have to click it several times for it to close.

Sometimes it closes on the first click, but also sometimes it can close after the 2 or 3 or 4 ... th click

## Expected behavior

By clicking just once it should close the popup.

## Live demo 

[Live démo : https://streamable.com/kws1xv](https://streamable.com/kws1xv) (you will see the bug at the end of the video I press twice)

It must be reproduced on an iPhone 8 / iOS 14.6 by going to this page with Safari: https://sweetalert2.github.io/
Take the example "A basic message" and click several times on "Try me" several dozen times, you will notice that sometimes it closes after the second time and in rare cases the popup will close after the 3rd or 4th time (in production on my site)

**Comment by limonte** [comment] 2021-05-30 09:25
Thank you for the report @Madriix! I'll take a look today.

**Comment by limonte** [comment] 2021-05-30 10:08
I am not able to reproduce the issue on iPhone 7 iOS 14.6. I will keep the issue opened in case someone else will confirm it.

**Comment by Madriix** [comment] 2021-05-30 20:17
Hi limonte
I just tested, you must sometimes click twice (or +) to simulate the bug.

I just reset Safari, and I returned to the https://sweetalert2.github.io/ page and in the "A basic message" demonstrable part, just click on the "Try me" button. "and press ok in the popup and you will see that sometimes you have to click 2 or more times to close the popup

**Comment by Madriix** [comment] 2021-05-30 20:48
I have news:

https://sweetalert2.github.io : The bug here occurs
https://sweetalert2.github.io/v10.html : The bug here also occurs
https://sweetalert2.github.io/v9.html : here impossible to reproduce the bug, I clicked on the button "try me" and "ok" about 50 times without success

**Comment by limonte** [comment] 2021-05-30 20:59
Thank you for the additional feedback @Madriix 

Unfortunately, I'm not able to reproduce the issue on iPhone 7. Tomorrow I'll try to find iPhone 8 and test there.

**Comment by Madriix** [comment] 2021-06-02 19:51
@limonte can you test the bug also via another way:
you do not click on the "Ok" button, instead you occasionally press on the gray space below the popup:
![Sans titre-1](https://user-images.githubusercontent.com/9107640/120543300-75bdc000-c3ec-11eb-92a0-aedcceb54a70.jpg)

the popup will not close every now and then, you need to test about 3 to 20 times

**Comment by brunosoaresds** [comment] 2021-07-20 17:19
Same here, on safari for iOS 14 seems to never work all buttons

**Comment by Madriix** [comment] 2021-07-24 16:45
@limote is the problem resolved? in test the last version I can not reproduce the bug (or not too much), it seems corrected or not?

**Comment by brunosoaresds** [comment] 2021-07-26 13:32
The problem was not resolved yet. But i have created a workaround by creating a fake swal before and instantly hiding it:
`
      # Create first fake swal...
      Swal.fire({
        title: '',
        didOpen: () => {
          (window as any).$('.swal2-modal').hide();
          # Create the real swal...
          Swal.fire({
            title: 'Erro!',
            text: 'Cliente não encontrado no sistema!',
            icon: 'error',
            confirmButtonText: 'OK!'
          });
        }
`

**Comment by limonte** [comment] 2021-09-19 08:22
I'm happy that you've found a workaround. I'm still unable to reproduce the issue and since nobody else is complaining about I'm closing it.

**Closed by limonte** 2021-09-19 08:22 UTC
Labels: help wanted, platform: iOS
