### ISSUE TITLE
Alert shows behind React Dialogs

### ISSUE THREAD

**Issue by i23098** [sweetalert2/sweetalert2#2772] opened 2024-10-12 11:45 UTC
### Current behavior

opening a dialog for an error message using react dialogs makes the sweetalert2 message show behind it__

### Expected behavior

sweetalert2 should appear on top of all elements

### Live demo !!! THIS FIELD IS REQUIRED !!!

I did a small example project available at https://github.com/i23098/sweetalert2experiment

**Comment by i23098** [comment] 2024-10-12 11:45
maybe it's related to https://github.com/sweetalert2/sweetalert2/issues/2749 ?

**Comment by i23098** [comment] 2024-10-12 13:19
I raised issue with MUI (https://github.com/mui/material-ui/issues/44077) but even if they fix it, there's lots of code out there that still uses zIndex. I think sweetalert2 should detect if in use the DOM and, if so, adapt accordingly.

**Comment by limonte** [comment] 2024-10-12 13:53
duplicate of https://github.com/sweetalert2/sweetalert2/issues/665

**Closed by limonte** 2024-10-12 13:53 UTC
