### ISSUE TITLE
sweetalert‘input cannot be used together with bootstrap’modal

### ISSUE THREAD

**Issue by moonsundong** [sweetalert2/sweetalert2#1114] opened 2018-05-31 07:01 UTC
⚠⚠⚠ PLEASE CAREFULLY READ AND FOLLOW THE ISSUE TEMPLATE BELOW ⚠⚠⚠

sweetalert‘input cannot be used together with bootstrap’modal：
when I open a boostrap'modal ,then I click a button that in bootstrap'modal to open sweetalert2,sweetalert‘input cannot

**Comment by limonte** [comment] 2018-05-31 07:20
Duplicate of #1067

**Closed by limonte** 2018-05-31 07:21 UTC
