### ISSUE TITLE
Warning 'sweetalert2'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by barrymolavenet** [sweetalert2/sweetalert2#2583] opened 2023-01-06 04:51 UTC
Hi

I upgraded the angular 13 to 14 but when I run my project there is a warning.

Warning `sweetalert2`. CommonJS or AMD dependencies can cause optimization bailouts.

Can you help me to remove the warning in my angular project?
Thank you.

**Comment by limonte** [comment] 2023-01-06 09:43
duplicate of #2467

**Closed by limonte** 2023-01-06 09:43 UTC
