### ISSUE TITLE
iOS scroll position jumps when sweet alert opens

### ISSUE THREAD

**Issue by markusramsak** [sweetalert2/sweetalert2#1586] opened 2019-05-11 11:42 UTC
## Current behavior

I have scrolled for example 500px down und open a sweet alert - and now it jumps about 50px upwards. When I close the sweet alert, the scroll position gets restored correctly.

## Expected behavior

No jumping when opening sweet alert.

it seems that document.body.scrollTop doesn't work as expected on iOS in combination with address bar in Safari browser.

when I remove the two lines in iOSFix():
document.body.style.top = offset * -1 + 'px';
and
document.body.scrollTop = offset * -1;

it works for me as expected

**Comment by limonte** [comment] 2019-05-11 12:01
Do you experience this issue on https://sweetalert2.github.io

**Comment by markusramsak** [comment] 2019-05-11 12:05
> Do you experience this issue on https://sweetalert2.github.io
no, I also have a second project with simpler HTML and CSS where it works too.

In this project where I have this issue is more complex.

**Comment by limonte** [comment] 2019-05-11 12:07
Could you please try to track down the difference between the complex project and https://sweetalert2.github.io/ ?

I'd assume there are some styles on the `<body>` of the complex project which cause this issue.

**Comment by markusramsak** [comment] 2019-05-11 12:12
I tried ...

**Comment by limonte** [comment] 2019-05-11 12:55
I'm closing this issue because we're unable to reproduce it without a live demo or a working example.

@gverni I'll be more strict with issue-reports starting from now, all incomplete issues will be closed, I made the change in ISSUE_TEMPLATE as well: https://github.com/sweetalert2/sweetalert2/commit/40bd865bd74da37fb4cac6fe95058d7b89d8994b

Reportes need to DO THE WORK as well, so we can focus on actual work instead of asking them to provide more details.

**Closed by limonte** 2019-05-11 12:55 UTC

**Comment by markusramsak** [comment] 2019-05-11 14:23
I found the source problem. It occurs when css position is set to relative on body. Is there a workaround, so it works even when body position is relative?

**Comment by markusramsak** [comment] 2019-05-11 14:55
I fixed this issue for myself by never added "position: relative" to body but added a wrapper container div with class "body-container" which finally has "position: relative"

**Comment by limonte** [comment] 2019-05-11 14:58
another solution would be

```css
body.swal2-shown {
  position: static;
}
```

**Comment by markusramsak** [comment] 2019-05-11 15:00
but this would break my absolute positioned footer ...
