### ISSUE TITLE
Addon incompatibility

### ISSUE THREAD

**Issue by Stopi** [sweetalert2/sweetalert2#1257] opened 2018-10-19 03:15 UTC
When I call swal for the first time, it immediately close.
Then on next calls it works as it should.
Worst thing is if it's a prompt pop-up, then it chooses to validate automatically (not cancel).

How to reproduce ? Simply go to the [main website](https://sweetalert2.github.io) then click on the big blue button "Show success message".

After investigating on several environment, it happens to be a compatibility problem with a [Firefox addon](https://addons.mozilla.org/fr/firefox/addon/i-dont-care-about-cookies). Issue occurs on Linux and Windows.

Can you have a look at this ?

**Comment by Stopi** [comment] 2018-10-19 03:19
More infos :
- I don't have an OSX device to test this.
- I know this addon also exists on Google Chrome but I didn't test it.
- If you disable the addon for one website, then swal works properly on this website.

**Comment by limonte** [comment] 2018-10-19 05:16
Duplicate of https://github.com/sweetalert2/sweetalert2/issues/1240

**Closed by limonte** 2018-10-19 05:16 UTC

**Comment by limonte** [comment] 2018-11-02 13:10
Fixed in the latest release (2.9.3) of the "I don't care about cookie" extension 🎉
