### ISSUE TITLE
Sweet alert does not work on Internet Explorer 11

### ISSUE THREAD

**Issue by mohammad-shadmehr** [sweetalert2/sweetalert2#1145] opened 2018-06-29 03:51 UTC
I have upgraded the Sweet alert 1 to 2 and it is completely functional on Chrome and Edge but not IE 11.
I have already added the `<script src="https://unpkg.com/promise-polyfill"></script>` as per the documentation suggests but still no luck! Have found this `<script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>` from other issues and added it to the page but still does not work. I am getting Syntax error in the IE console near the .then() promise function.

By the way all types of sweet alert work fine even in IE 11 but the one with promise functions: .then()

Thanks for you inputs in advance...

**Comment by limonte** [comment] 2018-06-29 12:02
Duplicate of #892

**Closed by limonte** 2018-06-29 12:02 UTC

**Comment by moseci** [comment] 2020-06-14 14:20
i have the same problem. sweer alert 2 does not work on ES 11
