### ISSUE TITLE
SweetAlert2 with Electron

### ISSUE THREAD

**Issue by syedadeel2** [sweetalert2/sweetalert2#1928] opened 2020-03-25 10:34 UTC
## Current behavior

Sweetalert2 with the electron is throwing error 

`sweetalert2.all.js:231 SweetAlert2: SweetAlert2 requires document to initializ`

Version: "^9.10.3",
Framework: Angular 9

## Expected behavior

As this is working good if I run the app without electron as expected and with no special magic this should work with electron app as well.

## Live demo 

[https://prnt.sc/rmfaik](url)

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment] 2020-03-25 10:42
Duplicate of https://github.com/sweetalert2/sweetalert2/issues/1927

**Closed by limonte** 2020-03-25 10:42 UTC

**Comment by pjebs** [comment] 2020-09-22 02:53
For using sweetalert2 via the main process: https://github.com/rocketlaunchr/electron-alert
