### ISSUE TITLE
Popups are not stackable, opening a new modal closes the previous one

### ISSUE THREAD

**Issue by aabluedragon** [sweetalert2/sweetalert2#2499] opened 2022-09-13 15:27 UTC
## Current behavior

Opening a new modal closes the previous one.

## Expected behavior

When opening a new modal, instead of closing the previous one, it should stack on top.
Once the top modal is closed, the previous one should be presented, and so on... until the modal stack is empty.

## Live demo

https://codepen.io/aabluedragon/pen/JjvRzMJ

**Comment by limonte** [comment] 2022-09-13 17:30
Duplicate of https://github.com/sweetalert2/sweetalert2/issues/770

**Closed by limonte** 2022-09-13 17:30 UTC
