### ISSUE TITLE
where is stop war with palestine ? same you did for Ukraine war ?  

### ISSUE THREAD

**Issue by amerhamdan3** [sweetalert2/sweetalert2#2747] opened 2024-07-31 21:35 UTC
@limonte 

like here : 
https://github.com/sweetalert2/sweetalert2/pull/2428

and here ? 
#https://github.com/sweetalert2/sweetalert2/pull/2462

and you said : 
PS. I am against politics in software, but this isn't politics, this is war. Many people including women and children are dying every day and it has to be stopped by any means necessary.

why i cant see Free Palestine pop up ?

thanks

**Comment by limonte** [comment] 2024-08-01 08:26
duplicate of #2685

**Closed by limonte** 2024-08-01 08:26 UTC
