### ISSUE TITLE
Custom buttons option

### ISSUE THREAD

**Issue by xyingsoft** [sweetalert2/sweetalert2#2032] opened 2020-08-19 11:12 UTC
## New feature motivation

Easy to customize buttons for confirmation modal

## New feature description

Custom buttons option

## New feature implementation
Following is example code for usage.

```

swal("A wild Pikachu appeared! What do you want to do?", {
  buttons: {
    cancel: "Run away!",
    catch: {
      text: "Throw Pokéball!",
      value: "catch",
    },
    defeat: true,
  },
})
.then((value) => {
  switch (value) {
 
    case "defeat":
      swal("Pikachu fainted! You gained 500 XP!");
      break;
 
    case "catch":
      swal("Gotcha!", "Pikachu was caught!", "success");
      break;
 
    default:
      swal("Got away safely!");
  }
});
```

**Comment by limonte** [comment] 2020-08-19 21:10
Duplicate of https://github.com/sweetalert2/sweetalert2/issues/1881

**Closed by limonte** 2020-08-19 21:10 UTC
