### ISSUE TITLE
Page scrolls to top by hundreds pixels when sweetalert opens

### ISSUE THREAD

**Issue by redochka** [sweetalert2/sweetalert2#1059] opened 2018-04-17 08:56 UTC
See this screencast

http://nimb.ws/TbiYMW

**Comment by limonte** [comment] 2018-04-17 09:16
@redochka I guess something is wrong with the document height of your page. Further support will be provided after you follow https://github.com/sweetalert2/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by redochka** [comment] 2018-04-17 10:06
not sure how to create the fiddle to reproduce the bug. https://jsfiddle.net/ad3quksn/1134/#&togetherjs=DaemDl8VaB

the problem has something to do with the table width. I noticed when some table TD contain very long string, the problem happens.

is it ok to give you an URL with username/password of the page where the problem is happening?

**Comment by limonte** [comment] 2018-04-17 16:16
> is it ok to give you an URL with username/password of the page where the problem is happening?

Yes, feel free to send me testing credentials to limon.monte@gmail.com

**Comment by limonte** [comment] 2018-04-24 05:37
> It's a blocker for the publishing of the new documentation site.

The issue with Docusaurus has been fixed in https://github.com/facebook/Docusaurus/releases/tag/v1.0.12

>  Ideally there would be no requirements for the styles on the <html> or <body> elements of the page, but if there are, they need to be documented.

Probably we should add something like "Do not shoot to your own knee by setting the height on html/body less than the height of the actual document" :)

**Comment by limonte** [comment] 2018-04-24 06:08
> is it ok to give you an URL with username/password of the page where the problem is happening?

@redochka I didn't get any email from you, please either send credentials or update the issue description so I can help you.

**Comment by redochka** [comment] 2018-04-24 14:18
@limonte Sorry for the delay, test credentials sent to you by email

**Comment by zenflow** [comment] 2018-05-03 07:06
> Probably we should add something like "Do not shoot to your own knee by setting the height on html/body less than the height of the actual document, some plugins might rely os that"

I don't think it's a very common requirement, so I wouldn't phrase it like that. As far as web standards are concerned (not sure about some other libraries though) it's perfectly ok to have child elements rendered outside outside the bounds of their parent.

**Comment by limonte** [comment] 2018-05-17 10:17
> Sorry for the delay, test credentials sent to you by email

The link isn't working anymore.

Closing this as duplicate of https://github.com/sweetalert2/sweetalert2/issues/781

**Closed by limonte** 2018-05-17 10:17 UTC
Labels: domain: dom/css, type: bug

**Comment by redochka** [comment] 2018-05-17 21:39
that's my laptop test server, let me know when you need it, i will turn it on.

**Comment by limonte** [comment] 2018-05-17 21:58
@redochka please do so. But before that, upgrade sweetalert2 to the latest version. Thanks!

**Comment by limonte** [comment] 2018-05-21 05:35
@redochka ping

**Comment by limonte** [comment] 2018-05-24 10:46
> I don't think it's a very common requirement, so I wouldn't phrase it like that. As far as web standards are concerned (not sure about some other libraries though) it's perfectly ok to have child elements rendered outside outside the bounds of their parent.

@zenflow you're right here, I just published [v7.20.9](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.20.9) which contains the fix for #1107

**Comment by redochka** [comment] 2018-05-27 14:54
@limonte The bug has been fixed in fact once i updated to 7.21.0 however, i am noticing a different issue as shown here: http://nimb.ws/IkQT7d

The right container (which is loosing its position when sweetalert pops up) is sticky (using a stickyfill polyfill)

I tried with and without : `heightAuto: false`

Is this related to the same OP issue or is it a new issue (new github issue)?

**Comment by limonte** [comment] 2018-05-27 16:43
> The bug has been fixed in fact once i updated to 7.21.0 however

Great, thanks for the confirmation! :tada: 

> i am noticing a different issue as shown here: http://nimb.ws/IkQT7d
> The right container (which is loosing its position when sweetalert pops up) is sticky (using a stickyfill polyfill)
> I tried with and without : heightAuto: false
> Is this related to the same OP issue or is it a new issue (new github issue)?

The `heightAuto` parameter has nothing to do with sticky elements. This is indeed another issue which has been already reported https://github.com/sweetalert2/sweetalert2/issues/1002

**Comment by limonte** [comment] 2018-05-28 13:06
@redochka the issue with sticky elements is fixed in v7.20.1 :tada:
