### ISSUE TITLE
Readme getting flagged as phishing trojan on Windows?

### ISSUE THREAD

**Issue by iKlsR** [sweetalert2/sweetalert2#2071] opened 2020-10-01 16:55 UTC
Not sure what is happening, just booted and was greeted with this? 

![](https://i.imgur.com/pj1GD1Y.png)

After taking a look, maybe it's a url to one of the nsfw sponsors getting flagged...

**Comment by limonte** [comment] 2020-10-01 17:17
Can't reproduce. Win 10 + all updates.

**Comment by limonte** [comment] 2020-10-01 17:19
Checked with https://www.virustotal.com all is well:

![image](https://user-images.githubusercontent.com/6059356/94841942-60d6fa00-0423-11eb-86a4-548e81193dc0.png)

**Comment by iKlsR** [comment] 2020-10-01 17:29
Noted. I updated to latest and made a fresh yarn install so we'll see. Thanks.

**Comment by Bejasc** [comment] 2020-10-02 00:11
This is still an issue. 
**Note** We were targeting version 9 - without any issue previously. 

We were including it via the jsdelir CDN, using the following
`<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>`

I've recreated the file from scratch (same content), and run the file through VirusTotal 
![2020-10-02 09_34_31-VirusTotal](https://user-images.githubusercontent.com/12091874/94875092-e34ad280-0492-11eb-99ab-ef918432e417.png)

**Microsoft detects the issue on Virustotal.**

---

Using the same file, I've *removed* the `<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>` line, and run this file through virustotal. Interestingly, the virus is no longer detected.

![2020-10-02 09_34_41-VirusTotal](https://user-images.githubusercontent.com/12091874/94875125-01b0ce00-0493-11eb-8986-3670bcdcb19e.png)

---

Upon checking what the latest version was - we discovered we were a version behind.. (running v9 instead of v10). 
Now targeting version 10 with `<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>`, and running this file through virustotal, the scan is fine. 

![image](https://user-images.githubusercontent.com/12091874/94875194-3a50a780-0493-11eb-9c95-742679b697dc.png)

---

Windows Defender picked this up across all 6 of our Windows 10 dev machines

**Comment by Bejasc** [comment] 2020-10-02 00:11
@iKlsR please reopen this issue for visibility. 

This is still an ongoing issue.

**Comment by MinerProfitDevelopment** [comment] 2020-10-02 00:25
This is still an ongoing issue. + 1

**Comment by JessieCowie23** [comment] 2020-10-02 00:42
This is also happening for us +1

**Comment by Bejasc** [comment] 2020-10-02 01:09
@iKlsR an interesting theory regarding the NSFW sponsor. 

I've been running the readme file through virustotal again and again.

The *only thing* tripping it up is the existence of the example;
`<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>` in the readme file itself.

When this line is removed, the virus is no longer detected.

**Comment by iKlsR** [comment] 2020-10-02 01:45
@Bejasc I didn't delve into it too much as I needed to work and it was the one file so I just quarantined it at the time. More than likely a false positive but lets see where the investigation leads.

**Comment by limonte** [comment] 2020-10-02 06:20
I still can't reproduce. Any help with finding the exact cause of the issue would be welcome.

In order to reproduce I created a simple HTML file:

```html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
</body>
</html>
```

and uploaded it to virustotal. No viruses were detected.

**Comment by Tieantono** [comment] 2020-10-02 06:30
I also encountered this problem after installing the Windows Updates' security update. Running `pnpm install` with the defined package dependency version in `package.json` is `^9.11.0` and in `package-lock.json` is `9.11.0` will notify the Windows Defender that there is a virus.

I'm using Windows 10 Home 2004 with OS Build 19041.508.

**Comment by limonte** [comment] 2020-10-02 09:31
Any **concrete steps** to reproduce the issue are welcome, I'm sill unable to reproduce the issue (Windows 10 Build 19041.508 + all updates)

**Comment by Tieantono** [comment] 2020-10-02 09:34
I found this update was installed last night:
![image](https://user-images.githubusercontent.com/14927392/94909272-2033bb00-04cd-11eb-9b54-c83e2eda3ae7.png)
Could you please check if you have this update installed in your PC?

**Comment by limonte** [comment] 2020-10-02 09:38
Yes:

![image](https://user-images.githubusercontent.com/6059356/94909586-15b4f980-04ac-11eb-8a95-79540eb2868f.png)

**Comment by Tieantono** [comment] 2020-10-02 09:44
Welp, after you show me that screenshot, I immediately run the Windows Update again, installed a new security updates (the KB2267602) and the issue is gone.

I think MS has fixed the security update for this issue.

**Comment by Bejasc** [comment] 2020-10-02 09:48
I'm experiencing the same - after running the exact same file_ I did through virustotal ~9h ago - it is coming up clean.

**Comment by limonte** [comment] 2020-10-02 09:49
Thank you for the feedback @Tieantono and @Bejasc 

It's most probably the false positive caused by Windows Defender and luckily fixed very promptly.

**Comment by Bejasc** [comment] 2020-10-02 09:53
The concrete steps I took at the time were;

1. Take the raw copy of the readme directly from this repo (a copy targeting `sweetalert2@9`)
2. Run that file through VirusTotal - trojan found. 
3. Remove the `<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>`
4 Run through virus VirusTotal again - no trojan detected. 

---

**Notes:**
 - I initially thought one of the NSFW Sponsors may had been compromised too - through an elimination process (modifying file, running through VT multiple times) - the `<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>` line was isolated to be the cause. 
 - Targeting `sweetalert2@10` removed the issue
 - This was happening on a copy of the file we had locally, as well as taken from this history of this repo, as well as directly from the CDN. 
 - The error could be reproduced by extracting the single line (`<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>`) into a text file, and running it through VT.

Glad this seems to have cleared up now, but was very confusing at the time,

**Comment by limonte** [comment] 2020-10-02 09:58
## The cause

> the <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script> line in README was isolated to be the cause.

This is totally unexpected, but at least makes some sense. Thanks a lot @Bejasc!

**Comment by limonte** [comment] 2020-10-02 10:01
### People who commented in this thread please run the Windows Update again, ensure that the definition updates are up-to-date:

![image](https://user-images.githubusercontent.com/6059356/94911841-6712b800-04af-11eb-9f50-3278c7c94f91.png)

The issue should be gone.

**Comment by TheColdPot** [comment] 2020-10-03 06:52
You can check out `#usage` and `#nsfw-sponsors`

W... Wait, this was resolved?

**Comment by limonte** [comment] 2020-10-03 08:14
> W... Wait, this was resolved?

So it seems. I'll keep the issue opened for a couple of days in case it occurs again for someone.

**Comment by limonte** [comment] 2020-10-05 12:21
Seems that nobody is affected anymore by this issue. Closing.

**Closed by limonte** 2020-10-05 12:21 UTC
