### ISSUE TITLE
Content moves on hover in ie11

### ISSUE THREAD

**Issue by nincorada** [sweetalert2/sweetalert2#1999] opened 2020-06-10 08:13 UTC
![lang](https://user-images.githubusercontent.com/47456728/84243761-40fa8e00-ab35-11ea-927d-431d574eeef1.gif)

Any idea why the content moves? 
the title param is  " "

**Comment by limonte** [comment] 2020-06-10 10:20
Interesting, thanks for reporting!

Reproducible here: https://sweetalert2.github.io/#custom-html

![1](https://user-images.githubusercontent.com/6059356/84256832-20263e80-ab1d-11ea-930d-90eb99f5b69c.gif)

**Comment by fishonweb** [comment] 2020-10-21 06:57
I could take a look.

**Comment by limonte** [comment] 2020-10-21 06:58
> I could take a look.

Thank you @fishonweb! Go ahead!

**Comment by fishonweb** [comment] 2020-10-21 08:33
If I removed `background-image: linear-gradient($swal2-button-darken-hover, $swal2-button-darken-hover);` in `_core.scss` at line 229, the ugly move effect in IE11 disappear.

**Comment by limonte** [comment] 2020-10-21 08:54
> If I removed `background-image: linear-gradient($swal2-button-darken-hover, $swal2-button-darken-hover);` in `_core.scss` at line 229, the ugly move effect in IE11 disappear but I can't explain why.

That's at least something, now we know the cause! Thank you for investigation @fishonweb!

**Comment by limonte** [comment] 2021-05-03 08:27
Closing due to IE11 support removal in the upcoming major release.

**Closed by limonte** 2021-05-03 08:27 UTC
Labels: browser: IE11, help wanted
