### ISSUE TITLE
Display multiple toasts?

### ISSUE THREAD

**Issue by vismutx** [sweetalert2/sweetalert2#2383] opened 2022-01-15 21:58 UTC
Any possibility to display multiple toasts? I found on stackoverflow that some years ago it was not possible, but already 2022. 
Any solution?

**Comment by vismutx** [comment] 2022-01-15 23:58
And another terrible case.
If I have a confirm modal with input, and system send notification, that should be shown with toast... Confirm modal will be closed? Strange UX..

**Comment by limonte** [comment] 2022-01-16 09:12
Nothing has changed here, still only one popup at the time.

Duplicate of #770

**Closed by limonte** 2022-01-16 09:12 UTC
