### ISSUE TITLE
Loading button animation issue when setting `buttonsStyling` to `false`

### ISSUE THREAD

**Issue by maicol07** [sweetalert2/sweetalert2#1829] opened 2019-11-25 12:59 UTC
## Current behavior
As shown in the demo, swal2 loader is placed next button label and it don't replace it.

## Expected behavior
Standard behavior

## Live demo 
https://onyx-boa.glitch.me

**Comment by LukeSungukJung** [comment] 2019-11-29 10:04
can I try to fix it?

**Comment by gverni** [comment] 2019-12-01 15:44
@maicol07 the issue is not with the mixin, but because you are using `buttonsStyling: false`. Since you are replacing the styling of the buttons, you need to make sure the `color` of the `swal2-confirm` is set to `transparent` when the class `swal2-loading` is applied.

**Comment by maicol07** [comment] 2019-12-05 19:54
It doesn't work even with transparent (text is transparent)...

**Comment by gverni** [comment] 2019-12-18 20:39
@maicol7 I explained you why it doesn’t work. If you need help you need to explain exactly what your problem is (one sentence is not enough). Closing this issue for now as not a bug

**Closed** 2019-12-18 20:41 UTC
Labels: needs: feedback
