### ISSUE TITLE
swal is making my mobile chrome browser unresponsive and crashing 

### ISSUE THREAD

**Issue by shahzaib17** [sweetalert2/sweetalert2#2123] opened 2020-12-06 07:23 UTC
it works fine on desktop browser but on chrome browser of huawei p30 pro it gets stuck on alert box confirmation dialog and doesn't respond to the Ok or Cancel button

**Comment by limonte** [comment] 2020-12-09 09:54
Just tried https://sweetalert2.github.io/ in chrome on huawei p30 pro, all is well. This is most probably duplicate of https://github.com/sweetalert2/sweetalert2/issues/2051

**Closed by limonte** 2020-12-09 09:54 UTC
