### ISSUE TITLE
BUG: Click can trigger twice

### ISSUE THREAD

**Issue by zzxjl1** [sweetalert2/sweetalert2#1562] opened 2019-04-24 08:25 UTC
## Current behavior

click the button -》sweetalert2 modal pops up -》there is another button at the same position -》sweetalert2 thinks that button is clicked

## Expected behavior

click the button -》sweetalert2 modal pops up -》nothing happens until user click the button

**Comment by limonte** [comment] 2019-04-24 08:39
Please provide the live demo.

The template: https://sweetalert2.glitch.me/

Check https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue for instructions

**Comment by zzxjl1** [comment] 2019-04-24 14:15
A phone with it’s unqiue reslution where two buttons are relatively at the same space triggers the bug:
http://103.94.185.36/1.mp4
What it‘s supposed to be like： 
http://103.94.185.36/2.mp4

**Comment by zzxjl1** [comment] 2019-04-24 14:15
A phone with it’s unqiue reslution where two buttons are relatively at the same space triggers the bug:
http://103.94.185.36/1.mp4
What it‘s supposed to be like： 
http://103.94.185.36/2.mp4

**Comment by zzxjl1** [comment] 2019-04-24 14:21
What happens is that when i click the button with white border the red button pops up at the same place, then sweetalerts reacts as if the red button is clicked.I have tested with numerous devices，it seems isn‘t caused by a laggy hardware

**Comment by gverni** [comment] 2019-04-24 19:28
@zzxjl1 thanks for the video, but I still don't understand the issue. I don't see any red button popping up in the video 1.mp4. Could you share the live demo and the screen resolution you are using?

**Comment by gverni** [comment] 2019-04-24 19:48
@zzxjl1 I think i understood now. The button that fires the swal (the button with white border on green background) is in the same position as the blue (confirm) button of the swal. So as soon as swal open, it closes straight away as if the blue confirm button is pressed. Is this the issue? It would really help here if you could provide a link with a live example so we can d bu further.

Also, is the issue replicated on pc as well? Using google chrome you can emulate a mobile phone screen (see instructions [here](https://developers.google.com/web/tools/chrome-devtools/device-mode/)). It would be good if you can try.

**Comment by zzxjl1** [comment] 2019-04-25 03:40
On pc i only managed to triggered the bug once.
http://103.94.185.36/3.mp4

Web page extracted from our site:
http://103.94.185.36/1.html#1/1

**Comment by limonte** [comment] 2019-04-25 05:33
I'm not able to reproduce.

**Comment by zzxjl1** [comment] 2019-04-25 07:30
It might have something to do with the fullpage.js, i'm experimenting to add some delay before the modal pops up, though this still remains to be tested.

**Comment by gverni** [comment] 2019-04-25 08:41
@zzxjl1 I'm not able to reproduce it either (I tried both PC and mobile). Also the link you sent shows the swal of video 2.mp4 (which as far as I understand it does not trigger the issue). Can you confirm you see the issue with the link you sent?

**Comment by zzxjl1** [comment] 2019-04-25 08:45
This bug barely triggers, i sticked to it all day and it only got captured once.

**Comment by zzxjl1** [comment] 2019-04-25 08:47
I‘m trying to implement setTimeout before modal pops, so far so good but further testing is needed.

**Comment by zzxjl1** [comment] 2019-04-25 08:48
I really appreciate your excellent work.

**Comment by gverni** [comment] 2019-04-28 07:00
@zzxjl1 I'm closing this issue for now since we were not able to reproduce it.

**Closed by gverni** 2019-04-28 07:00 UTC
