### ISSUE TITLE
Button or other alert element in background

### ISSUE THREAD

**Issue by maicol07** [sweetalert2/sweetalert2#1725] opened 2019-08-27 09:34 UTC
## New feature motivation

Alert looks bad without this feature when we use a dropdown (see example)

## New feature description

Hide the buttons or any other element when overlayed by another element.
Screenshot of how it looks at the moment (example with intl tel input):
![immagine](https://user-images.githubusercontent.com/9463142/63759743-4cd6d580-c8be-11e9-97e8-26e8502ddafa.png)

## New feature implementation

Add a property to the Sweetalert2 fire method called hideOnOverlay where we add the element or, otherwise, an OverlayElements property with overlay elements id. Then when that overlay element is triggered, button's CSS display property will be set to none (and changed when overlay is dismissed)

**Comment by toverux** [comment] 2019-08-27 09:51
Hmm... This could be fixed with a simple z-index, no ? Give your dropdown a higher value than the alert (>1060), and if it's not working, make sure that they're in the same [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

**Comment by limonte** [comment] 2019-08-27 10:29
> The thing is, the buttons' container has z-index: 1 (not sure of the reason, probably @limonte knows better).

https://github.com/sweetalert2/sweetalert2/blob/master/src/sweetalert2.scss#L304

**Comment by maicol07** [comment] 2019-08-27 10:35
> Edit : Ah, sorry, it seems to just happen to the buttons, therefore I think your dropdown window is a direct child of the alert, which is even better for us. The thing is, the buttons' container has `z-index: 1` (not sure of the reason, probably @limonte knows better). It means that your dropdown must have a z-index of 2, at least.

The dropdown has already a z-index of 2: https://github.com/jackocnr/intl-tel-input/blob/129283a741cd379fd32038469eee79f3b701c16f/src/css/intlTelInput.scss#L124

**Comment by limonte** [comment] 2019-08-27 10:38
Please provide a working example in order for us to be able to reproduce the issue.  

The live demo template: https://sweetalert2.glitch.me/
Instructions: https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue

**Comment by maicol07** [comment] 2019-08-27 10:57
Here you are: https://vaulted-longan.glitch.me/
_Fun fact: I don't know why but glitch.me subdomains works only on my phone... I've tried on two PCs but none worked..._
Anyway, I've found out that on mobile works correctly (buttons get overlayed) but on desktop remain the issue

**Comment by toverux** [comment] 2019-08-27 14:55
Hm okay, the dropdown z-index is driven by the z-index of `.swal2-content`, which is still 1.
`.swal2-actions` has a z-index of 1 too, but since it appears later in the DOM, it's rendered above.
A solution could be to give a higher z-index value  to `.swal2-content` compared to `.swal2-actions` (there it works).
Removing all `z-index: 1` from inner elements could work too but it seems it's there for a reason. @limonte, when is [this situation](https://github.com/sweetalert2/sweetalert2/blob/master/src/sweetalert2.scss#L304) happening?

**Comment by limonte** [comment] 2019-08-28 07:26
For now, the solution would be to use the `customClass` parameter and add classname with `z-index: 2`  to `content` 

Docs: https://sweetalert2.github.io/#custom-class

**Closed by limonte** 2019-08-28 07:26 UTC
