### ISSUE TITLE
Unable to scroll to the top of the modal when using a long text

### ISSUE THREAD

**Issue by ClaudiuGeorgiu** [sweetalert2/sweetalert2#679] opened 2017-10-25 16:26 UTC
When opening a modal with a long text inside, I'm unable to scroll at the top of the modal window, so the first part of the text is not reachable.

Example: https://jsfiddle.net/ad3quksn/158/

This issue was introduced with the last version `6.11.0`, because it works as expected for the previous versions.

**Comment by limonte** [comment] 2017-10-26 05:14
Weird issue, many thanks for reporting @ClaudiuGeorgiu!

@acupajoe I was digging into this and it seems that the reason is removing `margin: auto` here: https://github.com/limonte/sweetalert2/commit/39968eccf8b3fbf4587f95efa78a6bc58a38ce76#diff-54aa44acced41a67c744578f847b1c34L49

I have no idea how exactly that margin works together with flexbox, but with `margin: auto` added to `swal2-modal` [this example](https://limonte.github.io/sweetalert2/#long-text) will work fine.

Flexbox experts, I need your help :sos:

**Comment by limonte** [comment] 2017-10-26 05:24
Fixes jsfiddle from the description: https://jsfiddle.net/ad3quksn/159/

**Comment by limonte** [comment] 2017-10-26 05:37
Simple jsfiddle demonstrates the issue: http://jsfiddle.net/9b2br2nz/

**Comment by limonte** [comment] 2017-10-26 07:50
I got inspired the other day by https://youtu.be/1-g1rvkORQ8?t=17m43s

Is it time to start using CSS Grid and flexbox as the fallback? :) http://jsfiddle.net/vk52g2p7/1/

What do you think, fellas? cc @acupajoe @toverux

**Comment by acupajoe** [comment] 2017-10-27 01:27
@limonte interesting... we need to add that into our test suite I think! I totally missed that one.

Adding `margin: auto` back in does work, but breaks `position` functionality (all modals will be centered as `margin: auto` overrides `justify-content` and `align-items`).

To add to the confusion - it looks like `align-items:flex-start` fixes it, but removes centering of the modal for normal cases. 

I'm looking into it further!

**Comment by limonte** [comment] 2017-10-29 08:51
Fixed in [v6.11.2](https://github.com/limonte/sweetalert2/releases/tag/v6.11.2), thanks for reporting!

**Comment by limonte** [comment] 2017-10-30 21:42
The issue is still present in IE11, reopening.

**Comment by limonte** [comment] 2017-10-31 06:49
I'm trying to fix this properly, asked a question on StackOverflow https://stackoverflow.com/q/47029346/1331425

Hopefully the Community will help :muscle:

**Comment by limonte** [comment] 2017-10-31 10:30
Unfortunately, no proper IE11 solution for now. Let's keep this issue opened to be fixed later.

**Comment by limonte** [comment] 2018-03-06 00:04
I'm closing this in favor of #933

**Closed by limonte** 2018-03-06 00:04 UTC
Labels: type: bug

**Comment by SchoppAx** [comment] 2019-02-18 12:09
Hi guys,

I still have the issue if I'm using any bottom positioning. 

Testet with the last release (8.2.0) on different browsers (like FF, Chrome, Safari): 
https://jsfiddle.net/1sLmb7j2/
