### ISSUE TITLE
component.ts depends on 'sweetalert2'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by vikujangid** [sweetalert2/sweetalert2#2496] opened 2022-09-07 12:57 UTC
I'm using it on Angular 14 and  getting an error

```
test.component.ts depends on 'sweetalert2'. CommonJS or AMD dependencies can cause optimization bailouts.
                                    For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

![image](https://user-images.githubusercontent.com/12443918/188883772-5794c49f-03a7-412a-85ba-1ff241b79e6d.png)

**Comment by limonte** [comment] 2022-09-09 11:36
duplicate of #2467

**Closed by limonte** 2022-09-09 11:36 UTC
