### ISSUE TITLE
Input swal with password creates chrome alert and triggers password manager

### ISSUE THREAD

**Issue by nicolasvahidzein** [sweetalert2/sweetalert2#1607] opened 2019-06-01 22:30 UTC
Hello Limonte, you had closed this one but it is not working. Issue was #1222.

Any changes to this issue since last year?

**Comment by gverni** [comment] 2019-06-02 17:22
Hi @nicolasvahidzein, I can't reproduce the issue. As you can see the `autocomplete` property is added to the `input` tag. 

![image](https://user-images.githubusercontent.com/17089396/58764789-5375db00-8563-11e9-8ea5-f60b40a7c5a0.png)

Can you provide more info as to what you see and why you think is not fixed?

**Comment by nicolasvahidzein** [comment] 2019-06-03 17:31
Hello, thank you for that, i will check for that right now. In the meantime, here is how i have it implemented.

![password prompt](https://user-images.githubusercontent.com/29876108/58821811-c9467900-862d-11e9-8f5f-ac9527fd6c61.jpg)
![password prompt2](https://user-images.githubusercontent.com/29876108/58821812-c9467900-862d-11e9-9052-0af095600f6d.jpg)

**Comment by nicolasvahidzein** [comment] 2019-06-03 17:34
I'm using this version. "sweetalert2": "^7.26.11",

You are right it is not added, could it be my version that i am using?

I am implementing it properly

![password prompt3](https://user-images.githubusercontent.com/29876108/58821961-2fcb9700-862e-11e9-800c-ff1a9a128a69.jpg)

**Comment by nicolasvahidzein** [comment] 2019-06-03 17:41
I am doing properly as far as i can tell.

```
heightAuto: alertAutoHeight,
inputAttributes: {
	autocomplete: 'off'
}
```

**Comment by gverni** [comment] 2019-06-04 08:05
> You are right it is not added, could it be my version that i am using?

@nicolasvahidzein I'm puzzled by this statement. In your screenshot i can see that the `autocomplete` property is added to the `input` tag. So what do you exactly mean by "is not added"?

**Comment by limonte** [comment] 2019-06-04 08:10
I guess @nicolasvahidzein is looking form this

```js
Swal.fire({
  input: 'password',
  inputAttributes: {
    'data-lpignore': true
  }
})
```

Taken from https://stackoverflow.com/a/44984917

Anyways, working with password managers has nothing to do with SweetAlert2, therefore I'm closing this issue.

**Closed by limonte** 2019-06-04 08:10 UTC
Labels: needs: feedback
