### ISSUE TITLE
Remove console.warn about backdrop being incompatible with toast

### ISSUE THREAD

**Issue by adwil13** [sweetalert2/sweetalert2#1192] opened 2018-08-02 11:51 UTC
Hey,

I just started using sweetalert2 to display toast messages in my webapp. By default when "toast: true" backdrop is shown (which is wrong imho). When I add "backdrop: false" everything works as expected (backdrop is gone), but I keep getting this console warning about backdrop being incompatible with toasts.
Another thing is that I'm getting 'allowOutsideClick is incompatible with backdrop false'' so I set it to false, but then there's another console warning 'allowOutsideClick is not compatible with toasts'.

Not a big issue but I really don't like seeing warnings about nothing.

Cheers

**Comment by limonte** [comment] 2018-08-03 08:08
Hello @adwil13 and thanks for reporting!

This is the duplicate of #1191, the issue has been fixed in `v7.26.10`, please upgrade your dependency.

**Closed by limonte** 2018-08-03 08:08 UTC

**Comment by lilz-sofia** [comment] 2023-06-30 03:28
Hey, I see this issue's been closed but the problem still exists. 
For my application, the backdrop for the toast really isn't showing, but the transparent backdrop element being there with higher z-index is blocking a button on the page from being clicked. So, I'm making the backdrop:false which results in producing this warning in the console.  @limonte
