### ISSUE TITLE
Sweet Alert 2 scrolling to top of page after firing with magnific popup ajax

### ISSUE THREAD

**Issue by mrdigitalau** [sweetalert2/sweetalert2#781] opened 2017-12-22 23:47 UTC
Hey Guys
Thanks for your hard work with this plugin, it's amazing.
I was wondering if you had ever experienced anything like this before?
I have a strange issue with my sweet alert 2 on a site i'm building.

I am building an online ordering system and I am currently making the functionality work so you click on a link which will take you to an AJAX Magnific  Popup of the product and it's options, you then click Add to cart which closes the magnific popup and also fires off a sweet alert to say the product has been added.

The problem being that when I fire the sweet alert from the AJAX popup, it scrolls my main page to the top every time. But, when I put a sweet alert 2 link in the actual document (as opposed to the ajax popup window), it doesn't scroll to the top.

See the screencast of it in action. http://screencasts.mrdigital.com.au/watch/cbl30E2P8e

I was wondering if you had any suggestion as to why it happens? I've been pulling my hair out :)

Thank you so much for any of your advice

**Comment by limonte** [comment] 2017-12-23 08:35
Hi @mrdigitalau and thanks for reporting this issue!

Could you please provide a simple [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/ad3quksn/249/

**Comment by limonte** [comment] 2017-12-30 10:43
I'm closing this issue due to inactivity, leave a comment with a jsfiddle if you think it should be reopened.

**Comment by shubhsnov** [comment] 2017-12-30 13:42
Facing a similar issue, which sort of seems like some issue with foundation, as it doesn't happen when I remove that dependency. Created a fiddle with relevant external libraries that I am using.

https://jsfiddle.net/d33uzanv/

**Comment by johncederholm** [comment] 2017-12-30 18:55
@shubhsnov @mrdigitalau  What browser are you two using?

https://stackoverflow.com/questions/28633221/document-body-scrolltop-firefox-returns-0-only-js/28633515

I think the problem lies with document.body.scrollTop, which should be modified according to the above answer. 

If I figure it out a good solution, I will submit a pull request.

**Comment by shubhsnov** [comment] 2017-12-30 19:43
For me, this is happening in both Firefox and Chrome. 

I don't know what foundation is doing in the background that is messing with the scrollTop, but yeah that is the only hint I have for now. It doesn't happen when I don't include foundation.

**Comment by prapats** [comment] 2017-12-31 17:44
Facing the same issue with sweetalert2@7.1.3

**Comment by shubhsnov** [comment] 2018-01-01 07:48
I could reproduce it back to 6.11.4

**Comment by limonte** [comment] 2018-01-01 10:25
@shubhsnov you issue is totally unrelated to SweetAlert2 but I'll help with your homework. 

1. you forgot to prevent default action in anchor click handler
2. you are including different versions of foundation (6.4.3 for js and 5.4.6 for css)

Here's the fixed jsfiddle: https://jsfiddle.net/limon/d33uzanv/10/

**Comment by shubhsnov** [comment] 2018-01-01 14:01
I don't think you read my above comments properly. I mentioned the preventDefault thing myself, and as for the version change thing, well I mistakenly updated the fiddle while I was trying different versions.

As for the issue being unrelated, I am not sure.  The bug is still present when I use 5.4.6 for both js and css. I assume a lot of people are still using v5 and below of foundation, and this issue would be there in terms of compatibility, as many people can jump from 5 to 6 directly(as is my case).

Anyways, here is a cleaner fiddle, where the issue still persists with foundation 5.4.6(and this is what I am using statically in my site, and the bug makes SweetAlert unusable), if you still want to have a go : https://jsfiddle.net/gvh2can8/

**Comment by cornelisonc** [comment] 2018-01-06 17:34
I was also experiencing this issue -- I'm not using Foundation, but it looks like the scrolling to the top issue is caused by adding a CSS attribute of `overflow-y: hidden` to the body. I tried a JSFiddle using only jQuery and SweetAlert2 and everything seemed to work fine, so I'm not sure what's causing it, but here is what fixed it for me:

`body.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown) {
  overflow-y: visible !important;
}`

Hopefully this will help someone.

**Comment by mrdigitalau** [comment] 2018-01-07 08:58
Hey cornelisonc,

Thanks heaps for that solution, it works an absolute charm :)

**Comment by mrdigitalau** [comment] 2018-01-07 08:59
Hey @cornelisonc ,

Thanks heaps for that solution, it works an absolute charm :)

**Comment by shubhsnov** [comment] 2018-01-10 07:59
@cornelisonc Thanks a lot! That worked for me too. :)

**Comment by queejie** [comment] 2018-01-12 14:30
@cornelisonc Thank you.  The style fix worked for us as well.  This is still a problem in v7.3.5.

**Comment by morning-bird** [comment] 2018-01-13 00:18
@cornelisons Thanks a lot.

**Comment by smithaa02** [comment] 2018-01-14 17:16
Thanks @cornelisonc !  This issue was giving me a lot of grief and this worked for me.  Would be great to see the developers add that little css line to their main release.

**Comment by limonte** [comment] 2018-01-15 07:28
I will reopen this issue because it affecting so many people and the suggested solution `body.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown) { overflow-y: visible !important; }` looks very hacky to me.

**PLEASE** everyone in this thread, **provide a jsfiddle with your case**. Without code, we can't help you much.

>JSFiddle template: https://jsfiddle.net/ad3quksn/249/

**Comment by limonte** [comment] 2018-01-17 07:57
I think I finally fixed this nasty issue! :tada: 

Please check out the latest release: https://github.com/sweetalert2/sweetalert2/releases/tag/v7.4.0

**Comment by limonte** [comment] 2018-01-17 12:01
If the fix in 7.4.0 works for you, please remove the suggested here hack:

```css
body.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown) { overflow-y: visible !important; }
```

since it depends on internal classnames which theoretically could be changed in one of next releases

**Comment by abrambailey** [comment] 2018-03-08 17:33
This seems to be an issue on mobile for me... even with 7.4.0

**Comment by pedro-lb** [comment] 2018-03-16 12:11
@limonte, solved for me in 7.4.0!

Many thanks.

**Comment by mitomm** [comment] 2018-05-08 00:34
I'm still having this scroll up issue with version 7.9.0 (even on desktop) - but only with Safari (tested on version 11.1). On Chrome everything is working fine.

**Comment by 7twin** [comment] 2018-05-16 05:34
Mobile chrome (android) is affected by this issue too

**Comment by 7twin** [comment] 2018-05-16 22:06
The linked "fixed" jsfiddles have the same issue too

**Comment by limonte** [comment] 2018-05-17 10:15
@7twin @mitomm @abrambailey guys, I would like to help you, but I can't reproduce the issue.

Could you please provide a bit more information about the document structure of your projects. If they are public provide a link. If not, provide either test credentials (my email limon.monte@gmail.com) or replicate the document structure in jsfiddle.

**Comment by 7twin** [comment] 2018-05-17 18:12
@limonte preventing default and returning false from the onclick function, makes it only jump ~50 pixels down and then back up, but it still does jump

**Comment by 7twin** [comment] 2018-05-17 19:35
@limonte sent you a mail with the title "SweetAlert2 scrollup issue" instead of a fiddle, it's much harder to create a fiddle

**Comment by limonte** [comment] 2018-05-17 20:45
Thanks a lot @7twin for the email with the code example! The issue should be fixed in the latest release (v7.20.6)

**Comment by 7twin** [comment] 2018-05-17 20:45
@limonte yes, just pulled the master and it's fixed, great job, thank you!

**Comment by limonte** [comment] 2018-05-17 20:55
Alright, closing the issue then. I think it's finally fixed.

**Closed** 2018-05-17 20:58 UTC
Labels: domain: dom/css, needs: feedback, severity2: broken, type: bug

**Comment by glendonyeo** [comment] 2018-05-24 03:33
@limonte unfortunately it doesn't seems fixed in my version

Please check the html copy on jsfiddle
https://jsfiddle.net/fk3psp83/

Running on SweetAlert v7.20.6, Having Issues on both Latest version of Chrome & Firefox

**Comment by glendonyeo** [comment] 2018-05-24 07:37
@limonte 
thanks for pointing out the issues,
for my case, the height:100% is set by google translation widget (just for other reference),

seems like the issues will appear when both body & html height is set to 100% 
(or similiar conditions like html {height:100%} , body {max-height:100%})
i am able to reproduce the issues @ sweetalert demo page by adding the css

**Comment by limonte** [comment] 2018-05-24 07:58
Thanks @glendonyeo! I reported another issue about this https://github.com/sweetalert2/sweetalert2/issues/1107

Subscribe to it to track the progress.

**Comment by limonte** [comment] 2018-05-24 10:44
I just released [v7.20.9](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.20.9) which contains the fix

@glendonyeo you can  remove `html{height: auto !important}` from your css :tada:

**Comment by glendonyeo** [comment] 2018-05-25 02:55
@limonte all is good from my side. hope this issues closed for real 😅

**Comment by infoeon** [comment] 2018-06-01 15:12
Not resolved in 7.21.1 per this fiddle: https://jsfiddle.net/ad3quksn/1189/

Removing the "overflow: auto" from the fiddle fixes the scroll issue, but we don't always have the opportunity to control that in style in certain sites.

**Comment by limonte** [comment] 2018-06-02 09:58
@infoeon whatäs the purpose of using `overflow: auto` on `html`?

**Comment by yangmingfa** [comment] 2019-03-11 02:09
Hey  @cornelisonc,
I also encountered this problem in the use of the project, refer to your suggestion, found that the use of swal2-show did not take effect, after reading the source code, changed to use swal2-in after the effective, I use the version is 5.3.3, thank you for your help!
`body.swal2-in:not(.swal2-no-backdrop):not(.swal2-toast-shown) {
  overflow-y: visible !important;
}`

**Comment by deksoke** [comment] 2019-03-21 04:15
I found this problem too
I fix by this css code
`/* fixbug sweetalert2 scroll to top when fire alert */
body.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown), html.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown) {
  height: 100% !important;
  overflow-y: visible !important;
}`

**Comment by Tawfeekamr** [comment] 2019-05-14 17:44
I think the major problem is in HTML when the acnhor element has ` <a href="#"> Click Me</a>"` , the `#` tells the browser to go to some where on the page! so before you install sweet alert the default action is to go to the top when you did not assign the anchor element target.

My problem just solved when I delete `href="#"` sweet alert working fine without any additional JavaScript or CSS.

**Comment by Pratysha** [comment] 2019-05-15 06:56
I cannot scroll to top or desired location using Swal.fire. Can you please help me with this.
if (!rateValidation) {
        window.scrollTo(0, 550);
        $('lblRateFactors').focus();
        Swal.fire({
          width: 350,
          text: 'Please complete the ratings for all factors',
          confirmButtonText: '<font color="black">Continue Rating</font>',
          animation: false,
          focusConfirm: false,
          confirmButtonColor: '#00CEDB'
        }).then();
        return false;
      }

**Comment by gverni** [comment] 2019-05-15 13:46
@Pratysha could you provide a live example for your issue along with an explanation of what you are trying to do? Also keep in mind that this specific issue may not have anything to do with what you are trying to achieve (if I understood your code)

**Comment by orrd** [comment] 2019-09-20 05:42
In case anyone else came across this issue with the page scrolling up when the dialog opens, there is now a solution where you can set `heightAuto: false` in your options to fix it.  (There was a reference to the pull request above, but it's easy to miss.)

**Comment by COLONEROz** [comment] 2020-05-20 08:16
i have a problem, i try to fix by last comment but dont work
![image](https://user-images.githubusercontent.com/15093800/82422617-deb9ea80-9aac-11ea-8bb8-4f14ebd50958.png)

when am click

![image](https://user-images.githubusercontent.com/15093800/82422652-eb3e4300-9aac-11ea-8a36-38d72105e167.png)

**Comment by limonte** [comment] 2022-06-07 13:42
> the problems still persists in latest version

please report the new issue with live demo, thanks

**Comment by rafalsk** [comment] 2022-06-08 07:32
there are issues on Stackoverflow without any resolution; we went ahead; overridden all on-click events and are hiding the pop-up ourselves.

**Comment by gyupm** [comment] 2023-10-20 01:40
Is this discussion still open?

**Comment by Miros-iStore** [comment] 2023-12-21 15:42
I have this bug in v11
in v10 all ok

**Comment by limonte** [comment] 2023-12-21 16:14
please report the new issue with the live demo, thanks
