### ISSUE TITLE
Popup with pre-defined and static content (without changing the DOM)?

### ISSUE THREAD

**Issue by dmitry-ivanov** [sweetalert2/sweetalert2#2284] opened 2021-06-29 11:33 UTC
Hi,

Is there a way to set popup contents in the page HTML, and use `Swal` just to toggle its visibility?

My use case is an `iframe` which is used for cross-domain communication _(via `Window.postMessage()` API)_. So, I want to create it once, and when it's needed - simply show/hide it to the user, in the Swal modal window _(each time the same `iframe` HTMLElement literally)_.

I've tried passing the HTMLElement _(from `document.querySelector()`)_ to the [`html`](https://sweetalert2.github.io/#html) option - but it changes the DOM _(which causes unwanted side-effects in messaging between domains)_.

I've also tried [`Declarative template`](https://sweetalert2.github.io/#didDestroy) - but it also creates a new `iframe` each time based on the given template.

Is there a way to have "static modal contents" in Swal?

Thank you!

**Comment by limonte** [comment] 2021-06-29 12:08
Thanks for reporting @dmitry-ivanov 

Could you please demonstrate these two cases with live examples:

> I've tried passing the HTMLElement (from document.querySelector()) to the html option - but it changes the DOM (which causes unwanted side-effects in messaging between domains).

> I've also tried Declarative template - but it also creates a new iframe each time based on the given template.

The template is here: https://codepen.io/limonte/pen/JjoWRMx

**Comment by dmitry-ivanov** [comment] 2021-06-29 13:07
Thank you for your reply, @limonte!

I've tried to describe it a bit more here:
https://codepen.io/dmitry-g-ivanov/pen/QWvWoZo

PS: I think it's related to this conversation, which describes the way it works now:
https://github.com/sweetalert2/sweetalert2/issues/263

Just trying to understand if it's possible to use Swal according to my use case.

Thank you!

**Comment by limonte** [comment] 2021-06-29 20:10
The issue is actually unrelated to SweetAlert2, browsers will always re-render iframe when moving it in the DOM: https://stackoverflow.com/a/8318401/1331425

**Closed by limonte** 2021-06-29 20:10 UTC

**Comment by dmitry-ivanov** [comment] 2021-06-30 08:14
Thanks again for your reply!

But the question was rather - _can I use Swal to **not** move the `iframe` in the DOM (just show/hide it in the popup)._

**Comment by limonte** [comment] 2021-06-30 09:48
> Thanks again for your reply!
> 
> But the question was rather - _can I use Swal to **not** move the `iframe` in the DOM (just show/hide it in the popup)._

Answer to that question is no.
