### ISSUE TITLE
imcompatible with bootstrap

### ISSUE THREAD

**Issue by Taeboush** [sweetalert2/sweetalert2#1300] opened 2018-11-19 15:37 UTC
style of bootstrap@3.3.7 makes the window smaller. 
![qq 20181119201154](https://user-images.githubusercontent.com/36111319/48717244-f7e1a100-ec53-11e8-8f9e-8427be96aa92.png)
![qq 20181119201227](https://user-images.githubusercontent.com/36111319/48717282-092aad80-ec54-11e8-83a0-7a00f1c39ac1.png)

**Comment by limonte** [comment] 2018-11-19 16:44
Duplicate of #834

Reason: Bootstrap 3 is setting `font-size: 10px` for `html`.

Solution: 

```css
.swal2-popup {
  font-size: 1.6rem !important;
}
```

**Closed by limonte** 2018-11-19 16:44 UTC

**Comment by Taeboush** [comment] 2018-11-19 16:49
thankyou and sorry for not reading the previous issues.
