### ISSUE TITLE
Keyboard navigation is broken when swal is called inside a bootstrap modal

### ISSUE THREAD

**Issue by victornpb** [sweetalert2/sweetalert2#1067] opened 2018-04-27 03:41 UTC
When you launch it from within a bootstrap modal, it is not possible to focus the buttons, so <kbd>enter</kbd> or <kbd>tab</kbd> doesn't work.

Also pressing <kbd>esc</kbd> dismisses both the alert and the modal.

https://jsfiddle.net/Victornpb/c1eyd94v/

I understand that this is caused by the way bootstrap handles focus and keypresses, but considering how widespread bootstrap is compatibility is kinda expected.

**Comment by victornpb** [comment] 2018-04-27 04:16
bootstrap locks focus to only elements inside the modal, so using `swal({target: modalBodyElement})` makes buttons focusable again, but it puts the backdrop inside the modal, so clicking outside, actually triggers the modal to be dismissed. So the desired behavior would be to only put the swal box inside the target, and continue to append the backdrop to body.

And seconds issue is regarding <kbd>esc</kbd> key, swal should stop propagation.

**Comment by victornpb** [comment] 2018-04-27 04:37
```js
document.addEventListener('keydown', function(e){
     //if esc 
     e.preventDefault();	
     e.stopPropagation();
     
}, true); //use capture so it triggers before bootstrap
```

**Comment by limonte** [comment] 2018-04-29 08:09
Duplicate of https://github.com/sweetalert2/sweetalert2/issues/374

Check out https://github.com/sweetalert2/sweetalert2/issues/374#issuecomment-268802123 for the solution:

```js
$('#myModal').on('shown.bs.modal', function() {
    $(document).off('focusin.modal');
});
```
Here's the fixed jsfiddle: https://jsfiddle.net/c1eyd94v/1/

**Comment by victornpb** [comment] 2018-05-02 14:30
Not really a solution, because that allows user to focus on elements that are unreachable.
See jsfiddle: https://jsfiddle.net/Victornpb/c1eyd94v/2/
--------------
Anyway what about the <kbd>ESC</kbd> issue? do you want me o open a new issue just for that?

**Comment by limonte** [comment] 2018-05-02 15:07
> Not really a solution, because that allows user to focus on elements that are unreachable.
See jsfiddle: https://jsfiddle.net/Victornpb/c1eyd94v/2/

Nice jsfiddle, thanks! Reopening the issue.

> Anyway what about the ESC issue? do you want me o open a new issue just for that?

That would be nice, please follow the issue template - it's there for a reason.

**Closed** 2018-05-23 18:30 UTC
Labels: resolution: duplicate

**Comment by limonte** [comment] 2018-05-23 19:27
Hello @victornpb 

Esc propagation has been fixed, I just released 7.20.8.

Also, I made the keydown handler work in capture mode, but it didn't help. I guess Bootstrap is doing something bad in the `enforceFocus()` method, but I don't have time to investigate further.

**Comment by infoeon** [comment] 2018-06-04 19:50
The fix for this broke custom elements (javascript based autocomplete input fields, etc) within the content portion of the sweetalert. Potential fix would be to allow events for targets within the content of the swal:

`
var keydownHandler = function keydownHandler(e, innerParams) {
	var parentElement, targetElement = e.target, contentElement = getContent();
	while(parentElement = targetElement.parentElement){
		if(parentElement === contentElement){
			return;
		}
		targetElement = parentElement;
	}
	...
`

**Comment by limonte** [comment] 2018-06-21 08:29
Apologies for missing your comment @infoeon 

:warning: :warning: :warning: Starting from [v7.24.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.24.0), keydown handler will not work in capture mode by default, which means:

- custom elements will work nicely
- in order to get compatibility with Bootstap, set `keydownListenerCapture` parameter to `true`

**Comment by heyitshubham** [comment] 2023-08-28 10:27
Use this code to put the focus on 'ok' button or your defined button to close the sweetalert popup.
Swal.fire({
        title: 'test',
        icon: 'error',
        confirmButtonText: 'Ok',
        onOpen: (popup) => {
          const okButton = popup.querySelector('.swal2-confirm') as HTMLElement;
          if (okButton) {
            okButton.focus();
          }
        }
      })
