### ISSUE TITLE
Swal is open smaller when used with bootstrap

### ISSUE THREAD

**Issue by brabao** [sweetalert2/sweetalert2#855] opened 2018-01-26 13:05 UTC
Swal (`7.7.0`) is open smaller when used with bootstrap (`3.3.7`)

[Example](https://jsbin.com/fuguderizi/2/edit?html,output)

Does anyone know how to fixthis?
Thanks fo any help

**Comment by limonte** [comment] 2018-01-26 13:07
Duplicate of #834

Reason: Bootstrap 3 is setting `font-size: 10px` for `html`.

Solution: 

```css
.swal2-popup {
  font-size: 1.6rem !important;
}
```

**Closed** 2018-01-26 13:07 UTC

**Comment by epexa** [comment] 2018-02-02 21:57
my solution:
```css
.swal2-container {
  zoom: 1.5;
}
```

**Comment by FinesseRus** [comment] 2018-03-01 11:10
@limonte Your solution breaks icons:

![2018-03-01 21 09 23](https://user-images.githubusercontent.com/9006227/36841721-f75bf73c-1d94-11e8-9501-50f1a11bfdfb.png)
