### ISSUE TITLE
Problems with Swal2 and =>

### ISSUE THREAD

**Issue by FredyWenger** [sweetalert2/sweetalert2#1865] opened 2020-01-07 14:11 UTC
Hi
I have implemented Swal2 (congrats b.t.w.)  and it works in all browsers except IE 11... :-(
After investigate the problem, I have find out, that the **=>**don't work in IE11.
As I'm not really a JS specialist, my question: 
I have:  
**onClose: () => (window.history.back(1))**
in my code actually.
**How to change the code so that it works in all browsers?**
Thanks for a feedback soon...
And.. greetings  from Switzerland

**Comment by limonte** [comment] 2020-01-07 14:12
Duplicate of #892

**Closed by limonte** 2020-01-07 14:12 UTC

**Comment by FredyWenger** [comment] 2020-01-07 14:29
Yes, its a Duplicate, but #892 don't show a solution...
I have found the solution myself:
Created an JS function:
**function BrowserBack() {
  history.back(1);
}**
And changed the code from:
onClose: () => (window.history.back())
to:
**onClose: BrowserBack**
