### ISSUE TITLE
Question: SweetAlert open another alert with prevent closing previous alert

### ISSUE THREAD

**Issue by fakhamatia** [sweetalert2/sweetalert2#2387] opened 2022-01-19 14:09 UTC
I want to open another alert along with the previous alert and prevent closing the previous alert, But the previous alert closes and new open. I used [iziToast](https://izitoast.marcelodolza.com/) and I can do this but I want to use SweetAlert.

SweetAlert Example:
``` javascript
const swalToast = Swal.mixin({
  toast: true,
  iconColor: "white",
  customClass: { popup: "colored-toast" },
  showConfirmButton: false,
  timerProgressBar: true,
});

swalToast.fire({
  title: "One",
  position: "bottom",
  timer: 5000,
  icon: "info",
});

setTimeout(() => {
  swalToast.fire({
    title: "Two",
    position: "bottom",
    timer: 1500,
    icon: "info",
  });
}, 2000);
```

![f9qXs](https://user-images.githubusercontent.com/20030910/150146491-7e046bfd-0c68-4687-a0d8-4360c773f3ea.gif)

iziToast Example:
``` javascript
iziToast.info({
  position: "bottomCenter",
  title: "One",
  message: "",
  timeout: 5000,
});

setTimeout(() => {
  iziToast.info({
    position: "bottomCenter",
    title: "Two",
    message: "",
    timeout: 1500,
  });
}, 2000);
```

![XOAeN](https://user-images.githubusercontent.com/20030910/150146832-d2a040e7-3b65-41d8-8b36-20a9944f5147.gif)

[StackOverflow](https://stackoverflow.com/q/69604808/10695748)

**Comment by limonte** [comment] 2022-01-19 15:00
Unfortunately, that's not possible.

Duplicate of #770

**Closed by limonte** 2022-01-19 15:00 UTC
