### ISSUE TITLE
Is it possible to support multiple instances?

### ISSUE THREAD

**Issue by rxliuli** [sweetalert2/sweetalert2#2305] opened 2021-08-03 05:23 UTC
I have observed that SweetAlert2 currently has a globally unique instance, that is, if the `fire` method is called separately in two places, the latter will overwrite the former. Is it possible to solve this problem through multiple instances?

The specific usage scenario is that when I was writing the oil monkey script, when the website itself uses sweetalert2, some pop-up boxes I added will be overwritten by the website itself.

I tried the `mixin` function, but it just mixes in some default options, using `fire` will still interfere with each other.

**Comment by limonte** [comment] 2021-08-03 09:35
Unfortunately, no. 

Duplicate of #770

**Closed by limonte** 2021-08-03 09:35 UTC
