### ISSUE TITLE
New release not found build dist folder 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [sweetalert2/sweetalert2#2217] opened 2021-04-15 05:57 UTC
Hello 
please make dist folder in all release build 

Thank you

**Comment by limonte** [comment] 2021-04-15 09:55
Can you be more specific? **What exactly** is missing and **where exactly**?

**Comment by rajesh-smartwebtech** [comment] 2021-04-16 11:28
@limonte  Thanks for replay 

production build  `dist` folder is not found is in last release version

Here all release has not finally compiled js files in `dist` folder  
![image](https://user-images.githubusercontent.com/35251001/115017728-967d9500-9ed4-11eb-9af7-25c034321a96.png)


I hope you will be understanding 

Thank you

**Comment by limonte** [comment] 2021-04-16 11:32
Duplicate of #1606

**Comment by limonte** [comment] 2021-04-16 11:36
Actually, it should be possible to include the `dist` folder into GitHub releases.

**Comment by rajesh-smartwebtech** [comment] 2021-04-16 11:42
@limonte  I don't understand What exactly ?
with about last comment

**Comment by limonte** [comment] 2021-04-16 11:49
🎉 All files from the `dist` folder are available on GitHub releases starting from  https://github.com/sweetalert2/sweetalert2/releases/tag/v10.16.3

**Closed by limonte** 2021-04-16 11:49 UTC
