### ISSUE TITLE
Shouldn't customClass options defined in a Swal mixin and passed with a mixin call be merged?

### ISSUE THREAD

**Issue by earshinov** [sweetalert2/sweetalert2#2039] opened 2020-08-31 13:21 UTC
## Current behavior

StackBlitz demo: https://stackblitz.com/edit/swal-mixin-customclass-override?file=index.ts

```
const test = Swal.mixin({
  // ...
  customClass: {
    confirmButton: 'green',
    cancelButton: 'red',
  },
});
```

![image](https://user-images.githubusercontent.com/52021/91723755-eeb19200-eba4-11ea-8c3e-b7407faf1217.png)

```
test.fire({ title: 'Title', text: 'Text', customClass: { confirmButton: 'orange' }});
```

![image](https://user-images.githubusercontent.com/52021/91723837-0f79e780-eba5-11ea-8918-99b6a0c5834f.png)

`customClass: { confirmButton: ... }` in the `test.fire` call doesn't only override the confirm button class, but also clears the cancel button class defined in the mixin.

```
customClass: {
  confirmButton: 'green',
  cancelButton: 'red',
}
+
customClass: {
  confirmButton: 'orange'
}
=
customClass: {
  confirmButton: 'orange'
}
```

## Expected behavior

I don't know about you, but I would expect `customClass` declarations to be merged. That is, the cancel button class defined in the mixin should still take effect (unless explicitly overridden in the final `Swal.fire` call with `customClass: { cancelButton: '' }`).

```
customClass: {
  confirmButton: 'green',
  cancelButton: 'red',
}
+
customClass: {
  confirmButton: 'orange'
}
=
customClass: {
  confirmButton: 'orange'
  cancelButton: 'red',
}
```

## Live demo

StackBlitz: https://stackblitz.com/edit/swal-mixin-customclass-override?file=index.ts

**Comment by zenflow** [comment] 2020-08-31 17:26
Hi @earshinov I originally implemented the `.mixin` method (in [mixin.js](https://github.com/sweetalert2/sweetalert2/blob/7ac3ffaf83423d87344db563f9a1e374507ad7e1/src/staticMethods/mixin.js)).

When a swal is fired, the `.fire` options are shallow merged with the `.mixin` options. 

In other words, passing another value for the same option will simply override the previous value. 

That goes for *all* options. It's not perfect, but it keeps things **simple & predictable**. 

The problem is that for each option, there are multiple ways that two values could be merged...
 
For example, I can think 3 ways `customClass` values could be merged (each may be desired in different situations):
1. New value overrides previous value
2. New value is shallow merged with previous value (what you described in Expected Behavior)
3. Properties of new value are concatenated with properties of previous value (e.g. `{ confirmButton: 'green', cancelButton: 'red' }` + `{ confirmButton: 'large' }` = `{ confirmButton: 'green large', cancelButton: 'red' }`

**Comment by zenflow** [comment] 2020-08-31 17:44
@earshinov For this use-case you could use a custom enhancer, which is a lot more flexible than the `.mixin` method.

```js
// Define custom enhancer
export function withMergedCustomClass (ParentSwal, customClass) {
  return class extends ParentSwal {
    _main (params) {
      return super._main({
        ...params,
        customClass: {
          ...customClass,
          ...params.customClass,
        },
      })
    }
  }
}

// Then use it somewhere else
const MySwal = withMergedCustomClass(Swal, { confirmButton: 'green', cancelButton: 'red' })

MySwal.fire({ confirmButton: 'orange' }) 
// equivalent to 
Swal.fire({ confirmButton: 'orange', cancelButton: 'red' })
```

**Comment by earshinov** [comment] 2020-08-31 18:08
Hi @zenflow , thanks for your reply!

There is one reason why I consider deep merging better. Before version 9.0.0 there were separate options for `confirmButtonClass`, `cancelButtonClass` etc. If you take the code I gave in the description and adapt it to an older version of swal, you will get this:

```js
const test = Swal.mixin({
  // ...
  confirmButtonClass: 'green',
  cancelButtonClass: 'red',
});

test.fire({ 
  // ...
  confirmButtonClass: 'orange',
});
```

Here the `test.fire` call will override confirm button class to 'orange', but leave cancel button class intact. In my opinion, this discrepancy in behavior between <9.0.0 and 9.0.0 is an unnecessary backward incompatible change, only caused by the fact that 9.0.0 uses shallow merging strategy for aggregate options it introduces (`customClasses`, `hideClass` and maybe some others). Someone who needs to upgrade swal <9.0.0 to ≥9.0.0 is likely to change `confirmButtonClass`, `cancelButtonClass` etc. into `customClasses: { ... }` mechanically and only then discover that merging doesn't work as before.

It is possible to use a custom function instead of `swal.mixin` as you suggest, but deep merging, among the three options you listed, seems the most intuitive to me because it matches the behavior of swal <9.0.0. So I would prefer to have it out of the box. Although, it may already be too late to make such changes in `swal.mixin`...

Anyway, I am of course not insisting. I just wanted to hear your thoughts and motivation.

Before I forget, I would also like to suggest documenting this shallow merging strategy on https://sweetalert2.github.io/. Docs for `swal.mixin` are barely existent:

![image](https://user-images.githubusercontent.com/52021/91751039-cb9ad880-ebcc-11ea-9d48-0479c7c6c7d1.png)

**Comment by limonte** [comment] 2020-09-01 11:26
Thank you both @earshinov for raising this question and @zenflow for the detailed response with the code which helps users with this use-case.

@earshinov I understand your reasoning, but as well as @zenflow I'd like to keep things **simple** and leave the mixin logic as it is. Changing it would mean the breaking change for existing users which we don't want. v9.0.0 was released almost a year ago and you're the first one since then raising this concern, so I believe the majority is happy with the current approach.

But, I agree with you that it should be documented, here's the issue for that: https://github.com/sweetalert2/sweetalert2.github.io/issues/118

**Closed by limonte** 2020-09-01 11:26 UTC
