### ISSUE TITLE
Is it possible to render optgroup in selects with inputOptions somehow?

### ISSUE THREAD

**Issue by beejaz** [sweetalert2/sweetalert2#1736] opened 2019-09-15 09:19 UTC
Hi,

Is it possible to give inputOptions parameters somehow so it shows optgroup categories in select-box or is it only possible with html-option?
```
input: 'select',
  inputOptions: {
    apples: 'Apples',
    bananas: 'Bananas',
    grapes: 'Grapes',
    oranges: 'Oranges'
  },
  inputPlaceholder: 'Select a fruit',
```
with HTML it would be:
```
  title: 'Select with optgroip',
  html:
    '<select class="swal2-select"><optgroup label="Subgroup 1"><option>One</option>></optgroup><optgroup label="Subgroup 2"><option>Two</option>></optgroup></select>',
```

**Comment by limonte** [comment] 2019-09-16 20:49
Duplicate of #1589

**Closed by limonte** 2019-09-16 20:49 UTC
