### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by coilnovasince1985** [sweetalert2/sweetalert2#1787] opened 2019-10-30 04:38 UTC
I cant properly compile my angular app using

`node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --aot --build-optimizer --prod`

keep receiving the following error:

```
ERROR in ./node_modules/sweetalert2/dist/sweetalert2.all.js
Module build failed: RangeError: Maximum call stack size exceeded
    at skipSynthesizedParentheses (/Users/app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:73209:44)
```

I've seen this kind of issue previously and it has been closed without a solution

**Comment by gverni** [comment] 2019-10-30 08:54
@limonte @toverux shouldn't all the angular issues be open in https://github.com/sweetalert2/ngx-sweetalert2? I found an old issue with similar signature that was closed by a PR on this repo: #1101

**Comment by limonte** [comment] 2019-10-30 09:03
Closing in favor of https://github.com/sweetalert2/ngx-sweetalert2/issues/134

**Closed by limonte** 2019-10-30 09:03 UTC

**Comment by toverux** [comment] 2019-10-30 09:07
I was about to close the one on my repo in favor of this one, because the issue is with TypeScript (not Angular) and located in `sweetalert2.all.js` ^^

**Comment by coilnovasince1985** [comment] 2019-10-30 09:22
@limonte you closing issue which is currently exist
